<?php

namespace Container5BXqDix;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerupdateBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fac5BQ2.App\Controller\BookController::updateBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fac5BQ2.App\\Controller\\BookController::updateBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'serializer' => '?',
            'em' => '?',
            'bookRepository' => 'App\\Repository\\BookRepository',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]))->withContext('App\\Controller\\BookController::updateBook()', $container);
    }
}
