<?php

namespace Container5BXqDix;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllercreateBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9RgOmLd.App\Controller\BookController::createBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9RgOmLd.App\\Controller\\BookController::createBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'serializer' => '?',
            'em' => '?',
            'urlGenerator' => '?',
            'authorRepository' => 'App\\Repository\\AuthorRepository',
        ]))->withContext('App\\Controller\\BookController::createBook()', $container);
    }
}
