<?php

namespace Container7CBCJ1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KgYbDYFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kgYbDYF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kgYbDYF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController::getAllAuthors' => ['privates', '.service_locator.I6YUgLp.App\\Controller\\AuthorController::getAllAuthors()', 'getAuthorControllergetAllAuthorsService', true],
            'App\\Controller\\AuthorController::getAuthorDetail' => ['privates', '.service_locator.I6YUgLp.App\\Controller\\AuthorController::getAuthorDetail()', 'getAuthorControllergetAuthorDetailService', true],
            'App\\Controller\\AuthorController::deleteBooke' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AuthorController::deleteBooke()', 'getAuthorControllerdeleteBookeService', true],
            'App\\Controller\\AuthorController::createAuthor' => ['privates', '.service_locator.1HzkfZG.App\\Controller\\AuthorController::createAuthor()', 'getAuthorControllercreateAuthorService', true],
            'App\\Controller\\AuthorController::updateBook' => ['privates', '.service_locator.AoY1wqV.App\\Controller\\AuthorController::updateBook()', 'getAuthorControllerupdateBookService', true],
            'App\\Controller\\BookController::getAllBooks' => ['privates', '.service_locator.wG7UZwv.App\\Controller\\BookController::getAllBooks()', 'getBookControllergetAllBooksService', true],
            'App\\Controller\\BookController::getBookDetail' => ['privates', '.service_locator.wG7UZwv.App\\Controller\\BookController::getBookDetail()', 'getBookControllergetBookDetailService', true],
            'App\\Controller\\BookController::deleteBooke' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BookController::deleteBooke()', 'getBookControllerdeleteBookeService', true],
            'App\\Controller\\BookController::createBook' => ['privates', '.service_locator.9RgOmLd.App\\Controller\\BookController::createBook()', 'getBookControllercreateBookService', true],
            'App\\Controller\\BookController::updateBook' => ['privates', '.service_locator.fac5BQ2.App\\Controller\\BookController::updateBook()', 'getBookControllerupdateBookService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AuthorController:getAllAuthors' => ['privates', '.service_locator.I6YUgLp.App\\Controller\\AuthorController::getAllAuthors()', 'getAuthorControllergetAllAuthorsService', true],
            'App\\Controller\\AuthorController:getAuthorDetail' => ['privates', '.service_locator.I6YUgLp.App\\Controller\\AuthorController::getAuthorDetail()', 'getAuthorControllergetAuthorDetailService', true],
            'App\\Controller\\AuthorController:deleteBooke' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AuthorController::deleteBooke()', 'getAuthorControllerdeleteBookeService', true],
            'App\\Controller\\AuthorController:createAuthor' => ['privates', '.service_locator.1HzkfZG.App\\Controller\\AuthorController::createAuthor()', 'getAuthorControllercreateAuthorService', true],
            'App\\Controller\\AuthorController:updateBook' => ['privates', '.service_locator.AoY1wqV.App\\Controller\\AuthorController::updateBook()', 'getAuthorControllerupdateBookService', true],
            'App\\Controller\\BookController:getAllBooks' => ['privates', '.service_locator.wG7UZwv.App\\Controller\\BookController::getAllBooks()', 'getBookControllergetAllBooksService', true],
            'App\\Controller\\BookController:getBookDetail' => ['privates', '.service_locator.wG7UZwv.App\\Controller\\BookController::getBookDetail()', 'getBookControllergetBookDetailService', true],
            'App\\Controller\\BookController:deleteBooke' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\BookController::deleteBooke()', 'getBookControllerdeleteBookeService', true],
            'App\\Controller\\BookController:createBook' => ['privates', '.service_locator.9RgOmLd.App\\Controller\\BookController::createBook()', 'getBookControllercreateBookService', true],
            'App\\Controller\\BookController:updateBook' => ['privates', '.service_locator.fac5BQ2.App\\Controller\\BookController::updateBook()', 'getBookControllerupdateBookService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthorController::getAllAuthors' => '?',
            'App\\Controller\\AuthorController::getAuthorDetail' => '?',
            'App\\Controller\\AuthorController::deleteBooke' => '?',
            'App\\Controller\\AuthorController::createAuthor' => '?',
            'App\\Controller\\AuthorController::updateBook' => '?',
            'App\\Controller\\BookController::getAllBooks' => '?',
            'App\\Controller\\BookController::getBookDetail' => '?',
            'App\\Controller\\BookController::deleteBooke' => '?',
            'App\\Controller\\BookController::createBook' => '?',
            'App\\Controller\\BookController::updateBook' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthorController:getAllAuthors' => '?',
            'App\\Controller\\AuthorController:getAuthorDetail' => '?',
            'App\\Controller\\AuthorController:deleteBooke' => '?',
            'App\\Controller\\AuthorController:createAuthor' => '?',
            'App\\Controller\\AuthorController:updateBook' => '?',
            'App\\Controller\\BookController:getAllBooks' => '?',
            'App\\Controller\\BookController:getBookDetail' => '?',
            'App\\Controller\\BookController:deleteBooke' => '?',
            'App\\Controller\\BookController:createBook' => '?',
            'App\\Controller\\BookController:updateBook' => '?',
        ]);
    }
}
