<?php

namespace Container7CBCJ1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllergetAuthorDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I6YUgLp.App\Controller\AuthorController::getAuthorDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I6YUgLp.App\\Controller\\AuthorController::getAuthorDetail()'] = ($container->privates['.service_locator.I6YUgLp'] ?? $container->load('get_ServiceLocator_I6YUgLpService'))->withContext('App\\Controller\\AuthorController::getAuthorDetail()', $container);
    }
}
