<?php

namespace Container7CBCJ1y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllergetAllBooksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wG7UZwv.App\Controller\BookController::getAllBooks()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wG7UZwv.App\\Controller\\BookController::getAllBooks()'] = ($container->privates['.service_locator.wG7UZwv'] ?? $container->load('get_ServiceLocator_WG7UZwvService'))->withContext('App\\Controller\\BookController::getAllBooks()', $container);
    }
}
