<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7CBCJ1y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7CBCJ1y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7CBCJ1y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7CBCJ1y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7CBCJ1y\App_KernelDevDebugContainer([
    'container.build_hash' => '7CBCJ1y',
    'container.build_id' => 'e413d6be',
    'container.build_time' => 1770041289,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7CBCJ1y');
