<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'author' => [[], ['_controller' => 'App\\Controller\\AuthorController::getAllAuthors'], [], [['text', '/api/authors']], [], [], []],
    'author_details' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::getAuthorDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/authors']], [], [], []],
    'delete_authors' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::deleteBooke'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/authors']], [], [], []],
    'create_author' => [[], ['_controller' => 'App\\Controller\\AuthorController::createBook'], [], [['text', '/api/authors']], [], [], []],
    'book' => [[], ['_controller' => 'App\\Controller\\BookController::getAllBooks'], [], [['text', '/api/books']], [], [], []],
    'details' => [['id'], ['_controller' => 'App\\Controller\\BookController::getBookDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'delete_books' => [['id'], ['_controller' => 'App\\Controller\\BookController::deleteBooke'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'create_book' => [[], ['_controller' => 'App\\Controller\\BookController::createBook'], [], [['text', '/api/books']], [], [], []],
    'update_book' => [['id'], ['_controller' => 'App\\Controller\\BookController::updateBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'App\Controller\AuthorController::getAllAuthors' => [[], ['_controller' => 'App\\Controller\\AuthorController::getAllAuthors'], [], [['text', '/api/authors']], [], [], []],
    'App\Controller\AuthorController::getAuthorDetail' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::getAuthorDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/authors']], [], [], []],
    'App\Controller\AuthorController::deleteBooke' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::deleteBooke'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/authors']], [], [], []],
    'App\Controller\AuthorController::createBook' => [[], ['_controller' => 'App\\Controller\\AuthorController::createBook'], [], [['text', '/api/authors']], [], [], []],
    'App\Controller\BookController::getAllBooks' => [[], ['_controller' => 'App\\Controller\\BookController::getAllBooks'], [], [['text', '/api/books']], [], [], []],
    'App\Controller\BookController::getBookDetail' => [['id'], ['_controller' => 'App\\Controller\\BookController::getBookDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'App\Controller\BookController::deleteBooke' => [['id'], ['_controller' => 'App\\Controller\\BookController::deleteBooke'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'App\Controller\BookController::createBook' => [[], ['_controller' => 'App\\Controller\\BookController::createBook'], [], [['text', '/api/books']], [], [], []],
    'App\Controller\BookController::updateBook' => [['id'], ['_controller' => 'App\\Controller\\BookController::updateBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
];
